Replace `export let` with `export var`
When running through the `(require ... :reload)` example, I got an error message from Node:

SyntaxError: Identifier 'sayHello$$module$src$js$hello' has already been declared
    at /home/rei/repos/hello-es6/.cljs_node_repl/src/js/hello.js:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:26:33)
    at Object.exports.runInThisContext (vm.js:79:17)
    at nodeGlobalRequire (repl:85:6)
    at global.CLOSURE_IMPORT_SCRIPT (repl:75:3)
    at Object.goog.require (repl:21:8)
    at repl:1:6
    at ContextifyScript.Script.runInThisContext (vm.js:26:33)
    at Object.exports.runInThisContext (vm.js:79:17)
    at Domain.<anonymous> ([stdin]:50:34)

This was due to the fact that Node (my version is 7.4.0) disallows redefinining anything declared with a `let`.  Cf: https://github.com/nodejs/node/issues/6118

This commit replace any `export let` with an `export var` which can be refined without error.